---
# DB Check
- block:
    - name: "Check for DB compatibility for multi-node setup"
      debug:
        msg: "Database must be external for more than one Morpheus node."

    - meta: end_play
  when: (groups[morpheus_group] | length > 1) and 
        (not morpheus_mysql_external | default(false))

# RabbitMQ Check
- block:
    - name: "Check for RabbitMQ Clustering for multi-node setup"
      debug:
        msg: "RabbitMQ must be external for more than one Morpheus node."

    - meta: end_play
  when: (groups[morpheus_group] | length > 1) and 
        (not morpheus_rabbitmq_external | default(false))
