---
# This playbook installs Morpheus on SUSE Linux
- name: Install Morpheus on SUSE Linux
  hosts: all
  gather_facts: true
  become: true
  vars:
    morpheus_package_state: present
    morpheus_upgrade_flag: true  
    morpheus_package_suse_15: "morpheus-appliance-7.0.6-2.sles15.x86_64.rpm"  
    morpheus_disable_rpm_gpg_check: true
    morpheus_use_offline_package: false
    morpheus_offline_package_suse: "/morpheus-offline-appliance-suse.rpm" 

  tasks:
    - name: Upgrade flag check
      set_fact:
        morpheus_package_state: latest
      when: morpheus_upgrade_flag

    - name: Gather package facts
      package_facts:
        manager: auto

    # Block for SUSE 15.x installation
    - block:
        - name: Morpheus UI | Install Morpheus from SUSE repository
          zypper:
            name: "{{ morpheus_package_suse_15 }}"
            disable_gpg_check: "{{ morpheus_disable_rpm_gpg_check }}"
            state: present

        - name: Morpheus UI | Install Morpheus Offline
          zypper:
            name: "{{ morpheus_offline_package_suse }}"
            disable_gpg_check: "{{ morpheus_disable_rpm_gpg_check }}"
            state: present
          when: morpheus_use_offline_package

      when: (ansible_distribution == "SLES") and
            (ansible_distribution_major_version == "15") and
            (('morpheus-appliance' not in ansible_facts.packages) or
            (morpheus_upgrade_flag))

  
