---
dependency:
  name: galaxy
driver:
  name: ec2
platforms:
  - name: instance1
    image_owner: "125523088429"
    image_name: "CentOS Stream 8 x86_64 20210603"
    instance_type: t3.medium
    vpc_subnet_id: subnet-26c2de6b
    security_groups: [ "sg-39e96c21" ]
    tags:
      Name: molecule_instance1
    groups:
      - db
  - name: instance2
    image_owner: "125523088429"
    image_name: "CentOS Stream 8 x86_64 20210603"
    instance_type: t3.medium
    vpc_subnet_id: subnet-26c2de6b
    security_groups: [ "sg-39e96c21" ]
    tags:
      Name: molecule_instance2
    groups:
      - db
  - name: instance3
    image_owner: "125523088429"
    image_name: "CentOS Stream 8 x86_64 20210603"
    instance_type: t3.medium
    vpc_subnet_id: subnet-26c2de6b
    security_groups: [ "sg-39e96c21" ]
    tags:
      Name: molecule_instance3
    groups:
      - db
provisioner:
  name: ansible
verifier:
  name: ansible
